# Generated by Django 4.1.3 on 2022-11-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес')),
                ('contact', models.CharField(max_length=30, verbose_name='контакт')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='FireExtingusher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('repair_coast', models.PositiveIntegerField(verbose_name='Стоимость перезаряда')),
            ],
            options={
                'verbose_name': 'Огнетушитель',
                'verbose_name_plural': 'Огнетушители',
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирмы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair', models.BooleanField(default=False, verbose_name='Замена ЗПУ')),
                ('repair_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество замен')),
                ('date_input', models.DateField(auto_now_add=True, verbose_name='Дата приемки')),
                ('date_output', models.DateField(auto_now=True, verbose_name='Дата выдачи')),
                ('status', models.CharField(max_length=20, verbose_name='Состояние')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='workshop.client', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('fire_ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='workshop.fireextingusher', verbose_name='огнетушитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.order', verbose_name='партия')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='positions',
            field=models.ManyToManyField(through='workshop.Position', to='workshop.fireextingusher', verbose_name='Огнетушители'),
        ),
        migrations.AddField(
            model_name='client',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='workshop.firm', verbose_name='Организация'),
        ),
    ]
