# Generated by Django 4.1.3 on 2022-12-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='fire_ex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='workshop.fireextingusher', verbose_name='огнетушитель'),
        ),
    ]
