# Generated by Django 4.1.3 on 2022-12-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_position_fire_ex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='positions',
            new_name='fire_extingushers',
        ),
        migrations.AlterField(
            model_name='position',
            name='fire_ex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.fireextingusher', verbose_name='огнетушитель'),
        ),
    ]
