# Generated by Django 4.1.3 on 2022-12-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_rename_positions_order_fire_extingushers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('fire_ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='workshop.fireextingusher', verbose_name='огнетушитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='workshop.order', verbose_name='партия')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='Office',
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Отделение', 'verbose_name_plural': 'Отделения'},
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AlterField(
            model_name='order',
            name='fire_extingushers',
            field=models.ManyToManyField(through='workshop.OrderPosition', to='workshop.fireextingusher', verbose_name='Огнетушители'),
        ),
    ]
